import type { Metadata, Viewport } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/Providers";
import { Analytics } from "@vercel/analytics/react"

const GetLexendDeca = Manrope({
  variable: "--font-geist-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  viewportFit: "cover",
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
  // modal
}: Readonly<{
  children: React.ReactNode;
  // modal: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning dir="ltr" className="light" lang="en">
      <body
        className={`${GetLexendDeca.variable} overflow-x-hidden  antialiased`}
      >
        <Analytics />

        <Providers>
          {children}
          {/* {modal} */}
        </Providers>
      </body>
    </html>
  );
}
